CREATE TABLE group_chat (chat_id BIGINT PRIMARY KEY, title TEXT NOT NULL, active BOOLEAN NOT NULL,
  retention_days INT NOT NULL DEFAULT 90, nudged_at TIMESTAMP WITH TIME ZONE);
CREATE TABLE form (chat_id BIGINT NOT NULL REFERENCES group_chat(chat_id) ON DELETE CASCADE, version INT NOT NULL,
  schema_json TEXT NOT NULL, updated_by BIGINT NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY (chat_id, version));
CREATE TABLE form_session (user_id BIGINT NOT NULL, chat_id BIGINT NOT NULL REFERENCES group_chat(chat_id) ON DELETE CASCADE,
  form_version INT NOT NULL, step INT NOT NULL, answers BYTEA NOT NULL, lang TEXT,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL, touched_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY (user_id, chat_id));
CREATE TABLE submission (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT NOT NULL REFERENCES group_chat(chat_id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL, form_version INT, profile BYTEA NOT NULL, answers BYTEA, status TEXT NOT NULL,
  decided_by BIGINT, decided_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE INDEX submission_chat_status ON submission(chat_id, status);
CREATE TABLE review_message (submission_id BIGINT NOT NULL REFERENCES submission(id) ON DELETE CASCADE,
  admin_id BIGINT NOT NULL, message_id BIGINT NOT NULL, PRIMARY KEY (submission_id, admin_id));
CREATE TABLE bot_user (user_id BIGINT PRIMARY KEY, dm_ok BOOLEAN NOT NULL, lang TEXT);
CREATE TABLE canary (id INT PRIMARY KEY, sealed BYTEA NOT NULL);
